### ISSUE TITLE
Third level is connected

### ISSUE THREAD

**Issue by AlikKosarevskiy** [kongoon/yii2-orgchart#1]
Hello kongoon!!!
Nice repo!  But I can not understand why 3-d level of another branch is connected (marked on the screenshot) ?  Let me know, please, what I doing wrong.
![555](https://cloud.githubusercontent.com/assets/19498683/25267646/44054840-267e-11e7-9c27-9a76e8b8c5ff.JPG)

**Comment by kongoon** [comment]
You can override css to this.
`<style>
.google-visualization-orgchart-node {
    border: 0px;
}
</style>`
